version: '3.1'

services:
  proxy:
    image: minecraft-nginx-reverse-proxy
    build: ./src
    ports:
      - 25565:25565
    volumes:
      - ./src/minecraft.conf:/opt/nginx/stream.conf.d/minecraft.conf:ro
